name: "Lint"

runs:
  using: "composite"
  steps:
    - name: Install node in ${{ matrix.project }}
      run: cd ${{ matrix.project }} && npm ci --legacy-peer-deps
      shell: bash

    - name: Run Lint in ${{ matrix.project }}
      run: cd ${{ matrix.project }} && npm run lint
      shell: bash
