services:
  blockchain:
    image: trubudget/blockchain:${TAG}
    environment:
      BLOCKCHAIN_PORT: ${BLOCKCHAIN_PORT}
      CHAINNAME: ${CHAINNAME}
      MULTICHAIN_RPC_PASSWORD: ${MULTICHAIN_RPC_PASSWORD}
      MULTICHAIN_RPC_PORT: ${MULTICHAIN_RPC_PORT}
      ORGANIZATION: ${ORGANIZATION}
      P2P_PORT: ${P2P_PORT}
      MULTICHAIN_DIR: ${MULTICHAIN_DIR}
    # networks:
    #   mynetwork:
    #     ipv4_address: 172.20.0.11
    ports:
      - "${MULTICHAIN_RPC_PORT}:${MULTICHAIN_RPC_PORT}"
      - "${BLOCKCHAIN_PORT}:${BLOCKCHAIN_PORT}"
      - "${P2P_PORT}:${P2P_PORT}"
