# Change /tmp to the location where the .multichain content should be saved on your machine 
version: "3"
services:
  blockchain:
    volumes:
      - alpha-volume:${MULTICHAIN_DIR}

volumes:
  alpha-volume:
